---
  local_backend: false
  backend:
    name: github
    repo: TODO_COMPANY_REPO
  publish_mode: editorial_workflow
  collections:
    -
      label: Team member
      name: teammembers
      create: true
      identifier_field: name
      fields:
        -
          label: Name
          name: name
          widget: string
        -
          label: Visible
          name: visible
          widget: boolean
          default: true
        -
          label: Role
          name: role
        -
          label: Description
          name: description
        -
          label: image
          name: image
          widget: image
      folder: src/data/team
      extension: json
  media_folder: static/assets
  public_folder: assets
