---
  backend:
    name: github
    repo: rightinyourwheelhouse/wheelhouse-website
  collections:
    -
      create: true
      fields:
        -
          label: Name
          name: rame
          widget: string
        -
          label: Role
          name: role
      folder: team
      label: team
      name: team
  media_folder: static/assets
  public_folder: /assets
