---
  backend:
    name: github
    repo: rightinyourwheelhouse/wheelhouse-website
  # backend:
  #   name: proxy
  #   proxy_url: http://localhost:8081/api/v1
  #   branch: add-offices
  collections:
    -
      label: Team member
      name: teammembers
      create: true
      identifier_field: name
      fields:
        -
          label: Name
          name: name
          widget: string
        -
          label: Role
          name: role
        -
          label: Description
          name: description
        -
          label: image
          name: image
          widget: image
      folder: src/data/team
      extension: json
    -
        label: Office
        name: offices
        create: true
        identifier_field: name
        fields:
          -
            create: true
            label: Name
            name: name
          -
            label: Address
            name: address
            widget: string
          -
            label: Mail
            name: mail
            widget: string
          -
            label: Phone
            name: phone
            widget: string
          -
            label: Description
            name: description
            widget: markdown
          -
            label: How to reach
            name: howToReach
            widget: markdown
          -
            label: image
            name: image
            widget: image
        folder: src/data/offices
        extension: json
  media_folder: static/assets
  public_folder: assets
